
services:
  # --- NATS with JetStream ---
  nats:
    image: nats:latest
    ports:
      - "4222:4222" # Client port
      - "8222:8222" # Management HTTP port
    command: ["--js", "-m", "8222"]
    networks:
      - klenzo_network

  # --- Redis ---
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - klenzo_network

  # --- Databases ---
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: klenzo
      POSTGRES_PASSWORD: klenzo_password
      POSTGRES_DB: klenzo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data_klenzo
      - ./migrations/init-schemas.sql:/docker-entrypoint-initdb.d/init-schemas.sql
    networks:
      - klenzo_network
    

  # --- Object Storage ---
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: klenzo_admin
      MINIO_ROOT_PASSWORD: klenzo_password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - klenzo_network

  # --- Application Services ---
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - nats
    environment:
      - APP_NAME=api-gateway
      - NODE_ENV=development
      - NATS_SERVERS=nats://nats:4222
      - JWT_SECRET=secret_key
    networks:
      - klenzo_network

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - nats
    environment:
      - APP_NAME=auth-service
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=klenzo
      - DB_PASSWORD=klenzo_password
      - DB_NAME=klenzo_db
      - NATS_SERVERS=nats://nats:4222
      - JWT_SECRET=secret_key
    networks:
      - klenzo_network

  finance-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3002:3002"
    depends_on:
      - postgres
      - nats
    environment:
      - APP_NAME=finance-service
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=klenzo
      - DB_PASSWORD=klenzo_password
      - DB_NAME=klenzo_db
      - NATS_SERVERS=nats://nats:4222
      - JWT_SECRET=secret_key
    networks:
      - klenzo_network

volumes:
  minio_data:
  postgres_data:

networks:
  klenzo_network:
