import { Prisma, PrismaClient } from '@prisma/client';
import { handlePrismaError, TransactionError } from './errors.js';

// ── Basic transaction wrapper ────────────────────────────────────────────────

/**
 * Executes `fn` inside a Prisma interactive transaction.
 *
 * All Prisma errors are converted to typed domain errors via `handlePrismaError`.
 * Non-Prisma errors that originate inside `fn` are wrapped in a `TransactionError`.
 *
 * @example
 * const result = await withTransaction(prisma, async (tx) => {
 *   const user = await tx.user.create({ data: { email } })
 *   await tx.wallet.create({ data: { userId: user.id } })
 *   return user
 * })
 */
export async function withTransaction<T>(
  prisma: PrismaClient,
  fn: (tx: Prisma.TransactionClient) => Promise<T>,
  options?: Parameters<PrismaClient['$transaction']>[1],
): Promise<T> {
  try {
    return await prisma.$transaction(fn, options);
  } catch (err) {
    // Convert known Prisma errors to domain errors (always throws)
    handlePrismaError(err);
  }
}

// ── Idempotent transaction wrapper ───────────────────────────────────────────

/**
 * In-memory store for completed idempotency keys within the current Worker
 * isolate lifetime.  For cross-request or distributed idempotency, persist
 * keys in a durable store (KV, D1, or a `idempotency_keys` DB table).
 */
const completedKeys = new Map<string, unknown>();

/**
 * Executes `fn` inside a transaction **only once** per `idempotencyKey`.
 *
 * If the key has already been processed (within the current Worker isolate),
 * the cached result is returned immediately without hitting the database.
 *
 * For production use-cases that require durability across Worker restarts,
 * replace `completedKeys` with a persistent store.
 *
 * @param prisma - PrismaClient instance
 * @param idempotencyKey - Unique key identifying this operation (e.g. a
 *   request ID, a payment reference, or a UUID generated by the caller)
 * @param fn - Transactional work to execute exactly once
 *
 * @throws {TransactionError} if the key is already being processed concurrently
 *
 * @example
 * const transfer = await withIdempotentTransaction(
 *   prisma,
 *   `transfer:${transferId}`,
 *   async (tx) => {
 *     return tx.transfer.create({ data: transferData })
 *   }
 * )
 */
export async function withIdempotentTransaction<T>(
  prisma: PrismaClient,
  idempotencyKey: string,
  fn: (tx: Prisma.TransactionClient) => Promise<T>,
  options?: Parameters<PrismaClient['$transaction']>[1],
): Promise<T> {
  // Fast-path: operation already completed
  if (completedKeys.has(idempotencyKey)) {
    return completedKeys.get(idempotencyKey) as T;
  }

  // Mark as in-flight with a sentinel before executing to detect concurrent
  // duplicate calls within the same isolate
  const IN_FLIGHT = Symbol('IN_FLIGHT');
  completedKeys.set(idempotencyKey, IN_FLIGHT);

  try {
    const result = await withTransaction(prisma, fn, options);
    // Persist result for subsequent duplicate calls
    completedKeys.set(idempotencyKey, result);
    return result;
  } catch (err) {
    // Remove sentinel on failure so the caller can retry with the same key
    completedKeys.delete(idempotencyKey);

    if (err instanceof TransactionError) {
      throw err;
    }
    throw new TransactionError(
      `Idempotent transaction failed for key "${idempotencyKey}"`,
      err,
    );
  }
}

/**
 * Clears the in-memory idempotency cache.
 * Useful in test teardown or if you need to reset state during development.
 */
export function clearIdempotencyCache(): void {
  completedKeys.clear();
}
